### ISSUE TITLE
Wrong data type for radio signal IDs

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#10]
The radio signal ID attributes (_transmitted-radio-signal-id_, _expected-radio-signal-id_, _received-radio-signal-id_) have a wrong data type:
- They are of type _radio-signal-id-datatype-type_ which is basically an identity resp. an identity reference.
- They should use the existing _radio-signal-id-type_ grouping and thus be containers.

**Comment by openBackhaul** [comment]
AirInterfaceConfiguration::transmittedRadioSignalID, AirInterfaceConfiguration::expectedRadioSignalID and 
AirInterfaceStatus::receivedRadioSignalID shall be updated to be of RadioSignalIdType datatype.

**Comment by openBackhaul** [comment]
AirInterfaceConfiguration::transmittedRadioSignalID, AirInterfaceConfiguration::expectedRadioSignalID and
AirInterfaceStatus::receivedRadioSignalID attributes have been changed to be of RadioSignalIdType datatype.
