### ISSUE TITLE
Key for g-826-threshold-cross-alarm-list not unique

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#11]
The _g-826-threshold-cross-alarm-list_ has the _g-826-value-kind_ attribute as key. 
This key is not unique as there might be 2 entries in the list: one for each granularity period (15m / 24h).

**Comment by openBackhaul** [comment]
G826ThresholdCrossAlarmType::granularityPeriod::partOfObjectKey = 2 ; writeAllowed=Create_only; avcn=No, isInvantiant=true

**Comment by openBackhaul** [comment]
Following stereotypes haven been set for the G826ThresholdCrossAlarmType::granularityPeriod attribute partOfObjectKey== 2 , writeAllowed==Create_only , avcn==No , isInvantiant==true
