### ISSUE TITLE
Wrong key for xlts-threshold-cross-alarm-list

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#12]
The _xlts-threshold-cross-alarm-list_ has a key consisting of the 2 attributes
- _level-threshold-second-kind_ 
- _xlts-level_

The granularity period should be added to the key so that it consists of 
- _level-threshold-second-kind_ 
- _xlts-level_ (see below)
- _granularity-period_

Some network elements are able to handle 2 different power thresholds (e.g. Rx level 1+2). Such thresholds could be distinguished by the _xlts-level_ attribute in the key. However, this would make changing the value a little bit awkward because you would have to delete the entry for the old value and then create a new entry for the new value. It would probably be better to amend the values for _level-threshold-second-kind_. This would allow removing _xlts-level_ from the key.

**Comment by openBackhaul** [comment]
G826ThresholdCrossAlarmType::granularityPeriod::partOfObjectKey = 2 ; writeAllowed=Create_only; avcn=No, isInvantiant=true

XltsThresholdCrossAlarmType::granularityPeriod::partOfObjectKey = 2 ; writeAllowed=Create_only; avcn=No, isInvantiant=true
XltsThresholdCrossAlarmType::xltsLevel::partOfObjectKey = 3 ; writeAllowed=Create_only; avcn=No, isInvantiant=true
