### ISSUE TITLE
Transmission mode attributes as references instead of containers?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#13]
The following transmission mode attributes are currently defined as containers (each holding the full set of children):
- _transmission-mode-min_
- _transmission-mode-max_
- _transmission-mode-cur_

I would have expected the attributes to be references (_leafref_) to a transmission mode name in the _transmission-mode-list_.

**Comment by openBackhaul** [comment]
All associations (references in e.g. Configuration) on existing instances of classes, which are describing capabilities, shall be of aggregation type shared instead of none.

**Comment by openBackhaul** [comment]
Aggregation type changed to shared for 

    transmission-mode-min
    transmission-mode-max
    transmission-mode-cur
