### ISSUE TITLE
Conditional-Packages are read-only but should be read-write.

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/airInterface#14]
Looking to UML of Pacs (not only airInterface) - it looks like the Pacs are defined as read-only, which should not be the case.

Please see: (first line is the reference to a Pac.uml - second line is an ownedAttribute with a PAC-type and isReadOnly statemen a 'true'.

air-interface/src/main/resources/airInterface/AirInterface.uml:237:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_AEiosKMlEemOU89mRgVhCg" name="**_airInterface_Pac**" type="_GsvW-l9MEemkV8c3A5D8-A" **isReadOnly="true"** aggregation="composite" association="_AEb7AKMlEemOU89mRgVhCg"/>

ethernet-container/src/main/resources/EthernetContainer/EthernetContainer.uml:195:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_xhd9gKI3Eem31MmnPfrwaQ" name="**ethernetContainer_Pac**" type="_ENVvU2BvEemiq_YnKFzkFg" **isReadOnly="true"** aggregation="composite" association="_xhVaoKI3Eem31MmnPfrwaQ"/>

hybrid-mw-structure/src/main/resources/HybridMwStructure/HybridMwStructure.uml:186:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_OEFGEJc6EemlEoOPrSSr0g" name="**_hybridMwStructure_Pac**" type="_WKgpiV-SEemI8ps-yiNc8Q" **isReadOnly="true"** aggregation="composite" association="_OD8jMJc6EemlEoOPrSSr0g"/>

ip-interface/src/main/resources/IpInterface/IpInterface.uml:192:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_dubYMKI0EemambewrvJmVg" name="**_ipInterface_Pac**" type="_bpwlgRW9EembqYDTDwOcsQ" **isReadOnly="true"** aggregation="composite" association="_duUDcKI0EemambewrvJmVg"/>

l3vpn-profile/src/main/resources/L3vpnProfile/L3vpnProfile.uml:86:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_xd8ZIKSMEemNpozXx_71_g" name="**_l3vpn_Pac**" type="_bHwVEjbBEem1EL_1UEZsYQ" **isReadOnly="true"** aggregation="composite" association="_xd1EYKSMEemNpozXx_71_g"/>

mac-interface/src/main/resources/MacInterface/MacInterface.uml:171:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_2BJ-wJ5vEemxJoxK-03g3w" name="**_macInterface_Pac**" type="_e9fHk1E7Eembl8KFq0LDlA" **isReadOnly="true"** aggregation="composite" association="_2BCC8J5vEemxJoxK-03g3w"/>

pure-ethernet-structure/src/main/resources/pureEthernetStructure/PureEthernetStructure.uml:177:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_CmJCEpzrEemX7plL9q9caA" name="**_pureEthernetStructure_Pac**" type="_rQ9D-V-IEemI8ps-yiNc8Q" **isReadOnly="true"** aggregation="composite" association="_CmHz8JzrEemX7plL9q9caA"/>

qos-profile/src/main/resources/QosProfile/QosProfile.uml:83:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_pOya0KSWEemPirJ7EQQkGg" name="**_qosProfile_Pac**" type="_Sz4MsDEWEemIT48r1znVbQ" **isReadOnly="true"** aggregation="composite" association="_pOqfAKSWEemPirJ7EQQkGg"/>

tdm-container/src/main/resources/tdmContainer/TdmContainer.uml:189:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_pzK4gJ8rEemmk7bKUDgv9A" name="**_tdmContainer_Pac**" type="_11ijkmBjEemiq_YnKFzkFg" **isReadOnly="true"** aggregation="composite" association="_pzDjwJ8rEemmk7bKUDgv9A"/>

wire-interface/src/main/resources/wireInterface/WireInterface.uml:201:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_HVwaUZ2EEemRh9ZwWhYdUw" name="**_wireInterface_Pac**" type="_w-Abv2HAEembqusQnCFcag" **isReadOnly="true"** aggregation="composite" association="_HVvMMJ2EEemRh9ZwWhYdUw"/>

wred-profile/src/main/resources/WredProfile/WredProfile.uml:92:        
<ownedAttribute xmi:type="uml:Property" xmi:id="_fVEigKR8EemZx_PrWGDYjw" name="**_wredProfile_Pac**" type="_F9F7QFRnEem5ec_9KiA7Yg" **isReadOnly="true"** aggregation="composite" association="_fU900KR8EemZx_PrWGDYjw"/>

**Comment by michbin** [comment]
The observation is correct - the conditional packages are read-only:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">`
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>not-writable</error-app-tag>
    <error-path xmlns:air-interface="urn:onf:yang:air-interface" xmlns:core-model="urn:onf:yang:core-model">
    /rpc/edit-config/config/core-model:control-construct/core-model:logical-termination-point[core-model:uuid='xxx']/core-model:layer-protocol[core-model:local-id='yyy']/air-interface:air-interface-pac
  </error-path>
    <error-message xml:lang="en">object is not writable</error-message>
    <error-info>
      <bad-element>air-interface-pac</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>
```

**Comment by openBackhaul** [comment]
Seems to be redundant with issue x6 *LpSpec::_*_Pac attribute to be set on IsReadOnly:=False

**Comment by openBackhaul** [comment]
"AirInterfaceLpSpec::_airInterface_Pac has been configured to be IsReadOnly==False"
