### ISSUE TITLE
rx-channel-bandwidth parameter

### ISSUE THREAD

**Issue by rservadio** [openBackhaul/airInterface#17]
In the configuration section the rx-channel-bandwidth parameter is still present.
In our understanding it should be removed by AirInterface model 2.0

**Comment by openBackhaul** [comment]
SIAE and Nokia already confirmed that rxChannelBandwidth is not configurable at their devices.
If Ericsson and Ceragon would confirm, too, the attribute would just be deleted.

**Comment by openBackhaul** [comment]
rxChannelBandwidth attribute has been removed
