### ISSUE TITLE
transmission-mode leafref: relative path instead of absolute path

### ISSUE THREAD

**Issue by rservadio** [openBackhaul/airInterface#18]
In the **transmission-mode** leafref contined in:
- grouping **acm-threshold-cross-alarm-type** 
- and grouping **time-xstates-type**

there is a wrong path :

    leaf transmission-mode {
      type leafref {
        path "/air-interface:air-interface-lp-spec/air-interface:air-interface-pac/air-interface:air-interface-capability/air-interface:transmission-mode-list/air-interface:transmission-mode-name";
      }
    }   

    The right (absolute) path should be:

        path "/core-model:control-construct/core-model:logical-termination-point/core-model:layer-protocol/air-interface:air-interface-pac/air-interface:air-interface-capability/air-interface:transmission-mode-list/air-interface:transmission-mode-name"

**Comment by openBackhaul** [comment]
With the new augment statement, the root element changes from AirInterface_Pac to ControlConstruct.
The path statements in all leafref statements have to be adapted.

Martin will analyse, whether the UML is incomplete for the UML2YANG tool producing correct path statements.

**Comment by openBackhaul** [comment]
Relative paths became obsolete after deciding to stick with augmentation statement inside tech.spec.extensions.
