### ISSUE TITLE
object-id-ref datatype (UML and YANG)

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#19]
The datatype of 
- object-creation-notification::object-id-ref
- object-deletion-notification::object-id-ref
- attribute-value-changed-notification::object-id-ref
- problem-notification::object-id-ref
has been changed from String to yang:uuid.
This might be wrong, because "ref" might indicate a reference on an already existing uuid.
The value of such reference can by definition not be unique.
So String might be the correct datatype.

Proposal: Changing the datatype in the UML and the YANG back to String.

**Comment by alexandrustancu** [comment]
Why is this not a leafref, which points exactly to the UUID of the affected object ?

**Comment by openBackhaul** [comment]
Common decision on 21.11.2019:

All *Notification::objectIdRef attributes will become _objectIdRef attributes generated from shared associations to LTP class in UML. This applies on all notifications.

All *notification::object-id-ref leaf will become leafref to LTP.

Only object-deletion-notification::object-id-ref : leafref will be "require-instance false;"

**Comment by openBackhaul** [comment]
Shared associations between *Notifications and LTP added.
Resulting attributes named "_objectIdRef".

UML done. YANG still open.

**Comment by openBackhaul** [comment]
data type of all object-id-ref attributes changed towards leafref.
```
    leaf object-id-ref {
      type leafref {
        path "/core-model:control-construct/core-model:logical-termination-point/core-model:uuid";
      }
      config false;
    }
```
In case of object-deletion-notification, "require-instance false;" added.
