### ISSUE TITLE
Possible issues from redefining identities in the air-interface model

### ISSUE THREAD

**Issue by alexandrustancu** [openBackhaul/airInterface#21]
Redefining same identities that are already defined in the **core-model** (e.g. *OPERATIONAL_STATE* and *ADMINISTRATIVE_STATE*) might cause problems in the implementations of the NETCONF Server.

There is no enforcement about what namespace the identity is coming from, so it might be the case that undefined behaviour will appear.

For example: 
<operational-state xmlns:air-interface="urn:onf:yang:air-interface-2-0">air-interface:OPERATIONAL_STATE_DISABLED</operational-state>

An **operational-state** leaf from the **core-model** might point to the identity from the **air-interface** model. This is not restricted by the model itself, but it will not be valid from the NETCONF Server perspective.

**Proposed solution:** either remove the duplicate identities defined in the air-interface of modify them to extend the base identity from the core-model, it something new needs to be added.

**Comment by openBackhaul** [comment]
Potential solution:
OperationalState and AdministrativeState enumerations to be renamed towards OperationalStateType and AdministrativeStateType.

**Comment by demx8as6** [comment]
After first analysis: this issue is air-interface specific.

**Comment by openBackhaul** [comment]
OperationalState has been renamed towards OperationalStateType 
AdministrativeState has been renamed towards AdministrativeStateType

UML done. YANG still open.

**Comment by openBackhaul** [comment]
typedef and identities fixed for operational-state and administrative-state.

YANG fixed.
