### ISSUE TITLE
xlts-threshold-cross-alarm-list: Threshold cannot be identified if being changed

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#22]
If a device supports more than 1 XLTS threshold for a combination { _level-threshold-second-kind_, _granularity-period_ } then it is not possible to identify the affected threshold if the level (_xlts-level_) is changed.

The reason is that _xlts-level_ is part of the _xlts-threshold-cross-alarm-list_ key so that a changed _xlts-level_ is understood as referring to a new instance.

One solution might be to introduce a number for identifying the threshold (similar to _acm-threshold-cross-alarm-definition-number_) and add it to the key of _xlts-threshold-cross-alarm-list_.

**Comment by openBackhaul** [comment]
Potential Solutions might be adding:
XltsThresholdCrossAlarmType::xltsThresholdCrossAlarmDefinitionNumber or 
XltsThresholdCrossAlarmType::xltsThresholdCrossAlarmInstanceNumber
and defining it to be partOfObjectKey = 3
and to define XltsThresholdCrossAlarmType::xltsLevel being partOfObjectKey = 0

**Comment by openBackhaul** [comment]
Current modeling requires the XltsThresholdCrossAlarmType instance to be deleted and a new to be created for changing the XltsThresholdCrossAlarmType::xltsLevel .
This does not correspond to the device implementations.

**Comment by openBackhaul** [comment]
The new xltsThresholdCrossAlarmDefinitionNumber attribute has been added and set to be partOfObjectKey = 3 and XltsThresholdCrossAlarmType::xltsLevel has been set to be no object key (partOfObjectKey = 0) any more.

UML and YANG have already been corrected in this sense.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March: 
Just closing the issue

**Comment by openBackhaul** [comment]
Has been decided to be closed at the 5G-xhaul call on 31st of March 2021.
