### ISSUE TITLE
acm-threshold-cross-alarm-definition-number: incorrect unit

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#23]
The _acm-threshold-cross-alarm-definition-number_ attribute has a unit ("s") which does not make sense.

**Comment by openBackhaul** [comment]
Required solution:
unit tag to be deleted in the background (directly altering the .uml file).

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March: 
Just closing the issue

**Comment by openBackhaul** [comment]
Has been decided to be closed at the 5G-xhaul call on 31st of March 2021.
