### ISSUE TITLE
objectClass of CurrentPerformace and HistoricalPerformance data type is not needed

### ISSUE THREAD

**Issue by niloda** [openBackhaul/airInterface#26]
objectClass is a type of objectIdentifier that contains a DOT notation:

> "Values of this type are denoted as a sequence of numerical
      non-negative sub-identifier values.  Each sub-identifier
      value MUST NOT exceed 2^32-1 (4294967295).  Sub-identifiers
      are separated by single dots and without any intermediate
      whitespace."

In a context of YANG modules it becomes unnecessary, since the DOT notation is typical of the SMI (Structure of Management Information) operating in the SNMP protocol.

Proposed solution: remove this attribute from every technology specific model or better specify the meaning of this parameter (and change its type)

**Comment by openBackhaul** [comment]
objectClass has already been removed from the UML and the YANG.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March: 
Just closing the issue

**Comment by openBackhaul** [comment]
Has been decided to be closed at the 5G-xhaul call on 31st of March 2021.
