### ISSUE TITLE
TX or RX direction of the Performance Values

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#32]
On some devices Performance data for adaptive modulation (timeXStateList) is collected for the transmitter and on other for the receiver.
Some way to be found to identify the direction of the performance data.

(Maybe this is the attribute that make the AirInterfaceCurrentPerformance and the AirInterfaceHistoricalPerformances container always being present even if the lists are empty.)

**Comment by openBackhaul** [comment]
Capability attribute will be added

**Comment by michbin** [comment]
Is there any need for such an attribute? Would an application on higher layer change its behavior depending on the value of this attribute?

**Comment by openBackhaul** [comment]
AirInterfaceCapability::directionOfAcmPerformanceValues : Enumeration attribute and 
DirectionType datatype with values TX, RX, NONE added.

**Comment by openBackhaul** [comment]
AirInterfaceCapability::directionOfAcmPerformanceValues : Enumeration attribute and
DirectionType datatype with values TX, RX, NONE has already been added to UML and YANG.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March: 
Just closing the issue

**Comment by openBackhaul** [comment]
Has been decided to be closed at the 5G-xhaul call on 31st of March 2021.
