### ISSUE TITLE
g-826-threshold-cross-alarm-list - max-elements number

### ISSUE THREAD

**Issue by rservadio** [openBackhaul/airInterface#33]
"g-826-threshold-cross-alarm-list" is a list with two keys:
key1: g-826-value-kind
key2: granularity-period

"g-826-value-kind" can take 4 different values:
- G_826_TYPE_ES
- G_826_TYPE_SES
- G_826_TYPE_CSES
- G_826_TYPE_UAS

"granularity-period" can take 2 differnet values:
- GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN
- GRANULARITY_PERIOD_TYPE_PERIOD-24-HOURS

The combination of the two keys allows 4x2=8 different values but the list is defined with max-elements=6

**Comment by michbin** [comment]
Is there a need for `max-elements` at all?
Each key must be unique so there can't be more than 8 list entries in any case.

**Comment by openBackhaul** [comment]
Multiplicity changed to "*".

**Comment by openBackhaul** [comment]
Test

**Comment by openBackhaul** [comment]
The multiplicity has already been changed to [*] in the UML and the YANG.
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March:
Just closing the issue
