### ISSUE TITLE
xlts-threshold-cross-alarm-definition-number config false

### ISSUE THREAD

**Issue by rservadio** [openBackhaul/airInterface#34]
Module: air-interface.yang
Revision: 2020-01-17

The xlts-threshold-cross-alarm-list is a list with 3 keys:
- Key1: level-threshold-second-kind
- Key2: granularity-period
- Key3: xlts-threshold-cross-alarm-definition-number

In the yang file Key1 and Key2 are defined with "config true" while Key3 is defined with "config false".
RFC 7950 doesn't allow the definition of list containing keys with different "config" values and for this reason the yang validation fails.
In 5G-xHaul meeting (2020-01-19) it has been decided to define Key3 with "config true" as the other two.

**Comment by openBackhaul** [comment]
In the UML it's fine.

**Comment by openBackhaul** [comment]
The xlts-threshold-cross-alarm-definition-number has been set on IsReadOnly==false in the UML and config==true (as a default value, as the statement is not present) in the YANG
Existing implementations are basing on the corrected YANG.

Proposal to the 5G-xhaul call on 31st of March:
Just closing the issue

**Comment by openBackhaul** [comment]
Has been decided to be closed at the 5G-xhaul call on 31st of March 2021.
