### ISSUE TITLE
Different multiplicity at problemKindSeverityList and supportedAlarmList

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#36]
Should be same multiplicity at both attributes.

**Comment by openBackhaul** [comment]
Shouldn't supportedAlarmList anyway get [*]?

**Comment by openBackhaul** [comment]
Proposal:
- AirInterfaceConfiguration::problemKindSeverityList to get [*] multiplicity.
- Comment to be changed to "Every alarm, which is listed in AirInterfaceCapability::supportedAlarmList, shall be instantiated here for facilitating configuration of a severity level."

**Comment by demx8as6** [comment]
changed to "UML to b

**Comment by openBackhaul** [comment]
Obsoleted by issue #54.
