### ISSUE TITLE
Scope of transmission-mode-list/xpic-is-available?

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#37]
What is the scope of `transmission-mode-list/xpic-is-available`?
Does it apply to the transmission mode it is contained in?
Or does it apply to the interface in general as implied by the description in the Yang file?

**Comment by openBackhaul** [comment]
The current formulation of the comment is misleading. 
It has been forgotten to be updated after moving the attribute from the Capability class into the TransmissionMode class.

Proposal:
To change the formulation from:
"In case this air interface type is capable of XPIC, this field shall contain a 'true'. This information shall purely relate to capabilities of the equipment type, but not to the operational capability of a specific hardware composition on site. Means for example that this attribute might contain a 'true' statement, even if an additional cable would have been required to actually operate XPIC in a specific case."

towards:
"In case this transmission mode is capable of XPIC, this field shall contain a 'true'. This information shall purely relate to the capability of setting the respective administrative state and is independent from an instantaneous operational status change. Means for example that this attribute might contain a 'true' statement, even if an additional cable would have been required to actually operate XPIC at a specific microwave link."

**Comment by openBackhaul** [comment]
Fixed with AirInterface_2.0.0-tsp.220328.1245.
