### ISSUE TITLE
AcmThresholdCrossAlarmType::amountOfSeconds should be defined for raising AND clearing

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#38]
AcmThresholdCrossAlarmType only holds an attribute (amountOfSeconds) for raising an alarm.
The corresponding attribute for clearing the alarm is missing.

There are also no capability attributes that are describing minimum and maximum configurable values.

**Comment by openBackhaul** [comment]
Proposal to be decided at 5G-xhaul call on 7th of April:
- Renaming AcmThresholdCrossAlarmType::amountOfSeconds attribute towards AcmThresholdCrossAlarmType::secondsForRaisingAlarm
- Adding AcmThresholdCrossAlarmType::secondsForClearingAlarm : Int16 = -1 attribute
- Adding AirInterfaceCapability::AcmThresholdCrossAlarmsAreAvail : Boolean = false attribute

**Comment by PrathibaJee** [comment]
As per [issue#47](https://github.com/openBackhaul/airInterface/issues/47) , the Datatype of AcmThresholdCrossAlarmType::secondsForRaisingAlarm = -1 shall be increased from Integer16 to Integer32.
