### ISSUE TITLE
interfaceStatus, PowerIsUp, LinkIsUp, OperationalState and AdministrativeState at the LTP

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#46]
Values of these status attributes are not in synch for several implementations.
And even more problematic, they are not in synch across the different vendors' implementations.

Does it make sense having so many status attributes?

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 21st of July 2021:**
The radioPowerIsUp attribute shall be deleted (because it is not supported as an operative state attribute at the known implementations).

**Comment by openBackhaul** [comment]
**Result of discussion during DMIP call on 3rd of March 2022:**
Vendors to please double check, whether their implementations are able to represent more than just UP and DOWN in the AirInterfaceStatus::interfaceStatus attribute.
(If there would be no additional information compared with ENABLED and DISABLED from the OperationalState attribute at the LTP the AirInterfaceStatus::interfaceStatus attribute would be deleted from the modelling.)

**Comment by demx8as6** [comment]
ifOperStatus  (AirInterfaceStatus::interfaceStatus)
 up(1),        -- ready to pass packets                              LTP:operationalState = enabled
 down(2),                                                                        LTP:operationalState = disabled
 testing(3),   -- in some test mode                                 LTP:operationalState = enabled 
 unknown(4),   -- status can not be determined            LTP:operationalState = enabled vs disabled  
                              -- for some reason.
 dormant(5),                                                                   LTP:operationalState = enabled
 notPresent(6),    -- some component is missing           LTP:operationalState = disabled
 lowerLayerDown(7) -- down due to state of                LTP:operationalState = enabled

Added values by 
 adminDown                                                                  value should be removed from the model 
 not-yet-defined                                                            LTP:operationalState = disabled

This comment is not the  final one - it represents just notes during a meeting 2022-03-08.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 23rd of March 2022:**

* The "ADMIN_DOWN" value shall be deleted from the list.

* The comments of the remaining values shall be complemented by the following statements:
  * UP: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being available for use (means: ENABLED), while this value occurs.”
 
  * DOWN: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * TESTING: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * UNKNOWN: "While this value occurs, the LogicalTerminationPoint::operationalState attribute, which is expressing the availability of the logical layer for being used, might have either ENABLED or DISABLED as value."

  * DORMANT: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being available for use (means: ENABLED), while this value occurs.”

  * NOT_PRESENT: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * LOWER_LAYER_DOWN: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * NOT_YET_DEFINED: "While this value occurs, the LogicalTerminationPoint::operationalState attribute, which is expressing the availability of the logical layer for being used, might have either ENABLED or DISABLED as value."

**Comment by openBackhaul** [comment]
**Comment on the proposal above (9th of March 2022):**
LOWER_LAYER_DOWN will not occur in case of AirInterface and WireInterface.
How to handle that?
Keeping the value for having the same enumeration at all interfaces?
Or deleting the value from the enumeration in case of AirInterface and WireInterface.

**Comment by openBackhaul** [comment]
**Updated Proposal to the 5G-xhaul call on 23rd of March 2022:**

* The "ADMIN_DOWN" value shall be deleted from the list.
* **The "LOWER_LAYER_DOWN" value shall be deleted from the list, because the AirInterface layer does not have a serving layer.**

* The comments of the remaining values shall be complemented by the following statements:
  * UP: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being available for use (means: ENABLED), while this value occurs.”
 
  * DOWN: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * TESTING: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * UNKNOWN: "While this value occurs, the LogicalTerminationPoint::operationalState attribute, which is expressing the availability of the logical layer for being used, might have either ENABLED or DISABLED as value."

  * DORMANT: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being available for use (means: ENABLED), while this value occurs.”

  * NOT_PRESENT: "It is expected that the LogicalTerminationPoint::operationalState attribute is expressing this logical layer being NOT available for use (means: DISABLED), while this value occurs.”

  * NOT_YET_DEFINED: "While this value occurs, the LogicalTerminationPoint::operationalState attribute, which is expressing the availability of the logical layer for being used, might have either ENABLED or DISABLED as value."

**Comment by openBackhaul** [comment]
Fixed with AirInterface_2.0.0-tsp.220328.1245.
