### ISSUE TITLE
XltsThresholdCrossAlarmType :: amountOfSeconds cannot contain the number of seconds of a day

### ISSUE THREAD

**Issue by niloda** [openBackhaul/airInterface#48]
This attribute is defined as int16 in the current model, this means that it can contain a number between -32768 and +32767, not allowing to set a value equal to the maximum number of seconds of a day (86400) for instances related to 24 Hours .

Proposal: change the type from int16 to int32

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul-call on 12th of May 2021:**
Datatype of XltsThresholdCrossAlarmType :: amountOfSeconds = -1 shall be increased from Integer16 to Integer32.

**Comment by openBackhaul** [comment]
Fixed with AirInterface_2.0.0-tsp.220328.1245.
