### ISSUE TITLE
air-interface-2-0:air-interface-capability::transmission-mode-list::transmission-mode-label

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#49]
Transmission mode names represented on the LCT GUI (e.g. "4QAMStrong") cannot be mapped on detailed information about transmission modes (as represented in the Capability class) without extensive tables and complicated comparing of several transmission modes.

An transmission-mode-label attribute, which is showing the name of the transmission mode as it is represented on the LCT GUI, would solve the problem.

**Comment by openBackhaul** [comment]
Further analysis of the subject resulted in potentially several different names on the LCT GUI could be used for representing the same transmission mode.
If this would be confirmed by vendors, the new attribute should not be named transmission-mode-list::transmission-mode-label, but transmission-mode-label-list and be of * multiplicity.

**Comment by openBackhaul** [comment]
**Proposal**
Adding a transmission-mode::transmission-mode-label-list [*] attribute with the comment "Labels, which are identifying this transmission mode at the LCT GUI."

**Comment by DanielaSpreafico** [comment]
I don't understand how to fill this transmission-mode-list::transmission-mode-label-list labels for a specific transmission-mode-list instance.
We introduced the 'symbol-rate-reduction-factor' attribute to be able to select, for lower modulation values (BPSK, 4QAM) , the reduction factor (ex. 1/2 or 1/4) that means a reduction of channel bandwidth.
For this purpose, in case the device type is able to support it for E-band,  the list of transmission-mode-list instance could include instances for same channel-bandwidth value (ex. 1000Mhz), same modulation-scheme value (ex BPSK) but different symbol-rate-reduction-factor values (ex, 1, 2 and 4) .
As an example :
1 instance for  transmission-mode-name like 1000-256-1  , channel-bandwidth value = 1000Mhz,  modulation-scheme = 256, symbol-rate-reduction-factor=1  
1 instance for  transmission-mode-name like 1000-PSK-1, channel-bandwidth value = 1000Mhz,  modulation-scheme = BPSK, symbol-rate-reduction-factor=1  
1 instance for  transmission-mode-name like 1000-PSK-2, channel-bandwidth value = 1000Mhz,  modulation-scheme = BSPK,  symbol-rate-reduction-factor=2  
1 instance for  transmission-mode-name like 1000-PSK-4, channel-bandwidth value = 1000Mhz,  modulation-scheme = BSPK, symbol-rate-reduction-factor=4  
When transmission-mode-max = 1000-256-1 
           transmission-mode-min = 1000-PSK-2
means that we can reach the transmission-mode-min and in this case the bandwidth is reduced from 1000Mhz to 500Mhz.
The proposal could be to introduce a label to show in more clear way that the bandwidth is reduced, so for transmission-mode-name =1000-PSK-2 something like transmission-mode-label = '500Mhz@BPSK.
But why a list?

**Comment by openBackhaul** [comment]
**Proposal**
Adding a transmission-mode::transmission-mode-label="Transmission mode label not yet defined." [1] attribute with the comment "Label, which is identifying this transmission mode at the graphical user interface of the local craft terminal."

**Comment by openBackhaul** [comment]
Fixed with AirInterface_2.0.0-tsp.220328.1245.
