### ISSUE TITLE
AirInterfaceStatus::radioPowerIsUp is not supported

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/airInterface#52]
**Proposal to the 5G-xhaul call on 21st of July 2021:**
The radioPowerIsUp attribute shall be deleted (because it is not supported as an operative state attribute at the known implementations).

**Comment by demx8as6** [comment]
**Decision on the 5G-xhaul-call on 21st of July 2021:**
The radioPowerIsUp attribute shall be deleted (because it is not supported as an operative state attribute at the known implementations).

**Comment by openBackhaul** [comment]
Fixed with AirInterface_2.0.0-tsp.220328.1245.
