### ISSUE TITLE
Wrong leafref specifications

### ISSUE THREAD

**Issue by michbin** [openBackhaul/airInterface#9]
The leafref statements for the following elements are wrong:

- acm-threshold-cross-alarm-type/transmission-mode (line 1588)
- time-xstates-type/transmission-mode (line 1631)

The statements have following issues:

- They contain XPath expressions which refer to the _air-interface-lp-spec_ grouping. The expressions may only refer to data nodes.

- The XPath expressions must be either relative to the current node or absolute, starting with the root node (_control-construct_).

- It looks like a configurable node cannot refer to a non-configurable node:
"air-interface.yang:1588: error: the node is config, but refers to a non-config leaf 'transmission-mode-name' in module 'air-interface' defined at air-interface.yang:1010"

**Comment by demx8as6** [comment]
After feedback from IISOMI and reading RFC and googling, 
I was experimenting with different ideas, but the only “solution” I could find was “require-instance: false;”.

Checked Options:
-	Min-elements = 1 in the list -> same error
-	Must statement for the referencing leaf with type leafref 
      o	Direct xPath -> same error
      o	With Boolean() -> same error
-	When statement for the referencing leaf with type leafref 
      o	Direct xPath -> same error
      o	With Boolean() -> same error

Proposed soltuion:
Use "require-instnace: false;", please see related file in the following attachment. 

[require-instance.zip](https://github.com/openBackhaul/airInterface/files/3827172/require-instance.zip)

**Comment by openBackhaul** [comment]
Following corrections manually added to the YANG resulting from UML2YANG translation tool:
- paths corrected (now starting from core root).
- 'require-instance: false;' added to overcome problem with referencing a non-configurable node from a configurable node. 
- must statement added to assure values a defined in the capabilities.
